#!/usr/bin/env python
#-*- coding:utf-8 -*-
# FIXME: this should use the egg once its complete for now we are doing some sys.path
# changes, make this work
import sys, os
sys.path.append(os.path.abspath("."))

import logging
from lib.connection import Connection

# Setup logging
logging.basicConfig(level=logging.DEBUG)

# Create a connection
c = connection(logger=logging.getLogger("haigha"))
