#!/usr/bin/env python
#-*- coding:utf-8 -*-
# FIXME: this should use the egg once its complete for now we are doing some sys.path
# changes, make this work
import sys, os
sys.path.append(os.path.abspath(".."))

import logging
from haigha import Connection, Message
from haigha import event
import signal

def sigint_cb(*args):
  """callback when we get a SIGINT."""
  event.abort()
event.signal( signal.SIGINT, sigint_cb )

# Setup logging
logging.basicConfig(level=logging.DEBUG)

# Create a connection
c = Connection(logger=logging.getLogger("haigha"), debug=2)

def consumer(msg):
  print "CONSUMING ", str(msg)
  global ch
  ch.basic.cancel( consumer=consumer )

  ch.basic.publish( Message(body='hello'), exchange='foo', routing_key='no.matter' )

ch = c.channel()
ch.exchange.declare( 'foo', 'topic' )
ch.queue.declare( 'bar' )
ch.queue.bind(  'bar', 'foo', 'hello.world' )
ch.basic.consume( 'bar', consumer )

#ch.queue.delete( 'bar' )
#ch.exchange.delete( 'foo' )

event.dispatch()
