#!/usr/bin/env python
#-*- coding:utf-8 -*-
import unittest2 as unittest
import os

loader = unittest.TestLoader()
suite = loader.discover('test', pattern='*_test.py')

unittest.TextTestRunner(verbosity=2).run(suite)

